// Falk AdSolution - Copyright (c) 2003 by Falk eSolutions AG - All rights reserved
function lB(Ha)
{document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+Ha+'"></scr'+'ipt>');}function mB(Ia)
{if(Ia==-1)
return ';path=/';var Ja=new Date();Ja.setTime(parseInt(Ja.getTime(),10)+1000*60*parseInt(Ia,10));return ';path=/;expires='+Ja.toGMTString();}function nB(j,k,y)
{var i='&dlv='+Ads_nid+','+Ads_wid+','+Ads_iid+','+j+','+k+'&kid='+j+'&chw='+bA+'&tcs='+cA+y+vA+gA;i+='&dmn='+Ads_T[5];if(navigator.appVersion.substring(0,1)>'3')
{i+='&scx='+screen.width+'&scy='+screen.height+'&scc='+screen.colorDepth;if(navigator.javaEnabled())
i+='&jav=1';}if((Ads_wrd!='')&&(Ads_wrd.toLowerCase()!='[keyword]'))
{i+='&wrd='+escape(Ads_wrd);}var Ka='&sta=,,,,'+yB()+',,,,'+escape(Ads_T[7])+',';vB(1,'STA-Uri-Parameter',Ka);i+=Ka;return (Ads_Timestamp+i);}function oB(j,k,y)
{return '&rdm='+nB(j,k,y)+'&iid='+Ads_iid+'&bid='+k;}function pB()
{if(hA)
return kA[Ads_sec]+'/dat/dlv/aslcount.html;cmd=red&';else
return kA[Ads_sec]+'/dat/bgf/trpix.gif?';}function qB(i)
{var La;vB(1,'',pB()+i);if(typeof(document.getElementsByTagName)!='undefined'&&typeof(document.createElement)!='undefined')
La='<div id=Ads_Banner'+Ads_iid+' style="position:absolute;left:0;top:0;display:none;">'
else if(document.layers)
La='<layer id=Ads_Banner'+Ads_iid+' left="0" top="0" visibility="hide">';else
La='<div id=Ads_Banner'+Ads_iid+' style="position:absolute;left:0;top:0;visibility:hidden;">';if(hA)
La+='<iframe src="'+pB()+i+'" width="1" height="1" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0">';La+='<img src="'+pB()+i+'" width="1" height="1">';if(hA)
La+='</iframe>';La+=(document.layers?'</layer>':'</div>');return La;}function rB(v,i)
{v.document.write(qB(i));}function sB()
{return tB(Math.random()*100000000,8);}function tB(Ma,Na)
{var Oa='#'+(Ma+100000000);return Oa.substr(10-Na,Na);}function uB(Pa,Qa,Ra)
{var s;while((s=Pa.indexOf(Qa))!=-1)
Pa=Pa.substr(0,s)+Ra+Pa.substring(s+Qa.length,Pa.length);return Pa;}function vB(B,Pa,Sa)
{var Ta=new Date();if(Ads_debug==1)
{document.write(((B!=3)?'':'<br>')+'<font color=#0000ff>[DEBUG'+((Ta-iA)/1000)+']</font> ');if((B==0)||(B==3))
document.write('<b><big>'+Pa+'</big></b><br>');else if(B==1)
document.write(''+Pa+': &nbsp;<font color=#000080>'+Sa+'</font><br>');else
document.write('<b>'+Pa+'</b><br>');}else if((Ads_debug==2)&&(B==3))
document.write('<font color=#0000ff>[DEBUG'+((Ta-iA)/1000)+']</font> <b><big>'+Pa+'</big></b><br>');}function wB(Ua)
{var A='#'+(parseInt(Ua,10)+100000000);return A.substr(2,2)+'/'+A.substr(4,2)+'/'+A.substr(6,2)+'/'+A.substr(8,2);}function xB(Ma)
{var Va='0123456789ABCDEF';var Wa='';while(Ma>0)
{Wa=Va.substr(Ma%16,1)+Wa;Ma=parseInt(Ma/16,10);}return (Wa=='')?'0':Wa;}function yB()
{if(typeof(gintFlash)!='undefined')
return gintFlash;var Xa;gintFlash=0;if(((navigator.appName=="Netscape")&&(navigator.userAgent.indexOf("Mozilla")!=-1)&&(parseFloat(navigator.appVersion)>=4)&&(navigator.javaEnabled())&&navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin))
{Xa=navigator.plugins['Shockwave Flash'].description;Xa=Xa.substring(Xa.indexOf("."),-1);gintFlash=Xa.substr(-1);}else if(navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!=-1&&navigator.userAgent.indexOf("Windows")!=-1&&navigator.userAgent.indexOf("Windows 3")==-1&&document.all)
{document.write('<scr'+'ipt language=VBScript>\n cB=10\nintMinVersion=1\nDo\nOn Error Resume Next\n');document.write('bolFlash=(IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash."&cB)))\n');document.write('If bolFlash=true Then Exit Do\ncB=cB-1\nLoop While cB>=intMinVersion\n </scr'+'ipt>');gintFlash=cB;}return gintFlash;}// Falk AdSolution - Copyright (c) 2003 by Falk eSolutions AG - All rights reserved
var Ads_ModulMain=true;if(typeof(Ads_ModulEffects)=='undefined')
Ads_ModulEffects=false;var bA,cA,dA,eA,fA,gA,hA,iA;var jA=['http://a.as-us.falkag.net','https://s.as-us.falkag.net'];var kA=['http://red01.as-us.falkag.net','https://red01.as-us.falkag.net'];var lA=['http://red01.as-us.falkag.net/server/asldata.js','https://red01.as-us.falkag.net/server/asldata.js'];var mA=['http://a.as-us.falkag.net','https://s.as-us.falkag.net'];var nA=['http://a.as-us.falkag.net/dat/bgf/','https://s.as-us.falkag.net/dat/bgf/'];var oA=[];var pA=navigator.userAgent.toLowerCase();var qA=(pA.indexOf("msie")!=-1);var rA=((pA.indexOf("win")!=-1)||(pA.indexOf("16bit")!=-1));var sA=(pA.indexOf("mac")!=-1);var tA=(navigator.appName.indexOf('icrosoft')!=-1);var uA=(typeof(document.getElementsByTagName)!='undefined'&&typeof(document.createElement)!='undefined')?1:0;var vA='';var wA=0;var xA=[];var yA=[];var zA;var a=[];var b=[];var c=[];var d=[];var e=[];var f=[];var g=[];var Ads_LinkUrl,Ads_CountUrl,Ads_ClickUrl,Ads_T,iid,bid,rdm;var aB,bB,cB;var dB='toolbar=yes,directories=yes,status=yes,scrollbars=yes,resizable=yes,menubar=yes,location=yes';function gotoSite(){window.open(aB,'flashwin',dB);}function emosite(){window.open(aB,'flashwin',dB);}function FlashClick(){window.open(aB,'flashwin',dB);}function link1(){window.open(aB,'flashwin',dB);}function gotoURL(h){window.open(bB+escape(h),'flashwin',dB);}function eB()
{Ads_kid=0;Ads_bid=0;Ads_cmd='';}function fB(h)
{vB(1,'adsclickurl',Ads_ClickUrl);h=uB(h,'[par]',escape(Ads_par));h=uB(h,'[keyword]',escape(Ads_wrd));h=uB(h,'[timestamp]',Ads_Timestamp);h=uB(h,'[clickurl]',escape(Ads_CountUrl));h=uB(h,'[clickurl_plain]',Ads_CountUrl);h=uB(h,'[web_id]',Ads_wid);h=uB(h,'[web_external_id]',escape(Ads_xwid));h=uB(h,'[con_id]',Ads_iid);h=uB(h,'[con_external_id]',escape(Ads_xiid));return h;}function gB()
{return kA[Ads_sec]+'/dat/dlv/aslcount.html?cmd=url&';}function hB(h,i)
{return gB()+i+'&dat='+escape(h);}function iB(j,k,l,m,n)
{var o;if(wA<2)
{wA++;o=wA+1;vA+='&kid'+o+'='+j;vA+='&bid'+o+'='+k;vA+='&iid'+o+'='+Ads_iid;vA+='&dlv'+o+'='+Ads_nid+','+Ads_wid+','+Ads_iid+','+j+','+k;if(fA!=0)
vA+='&sid'+o+'='+fA;arrIntern=l.split('-');Ads_iid=arrIntern[1];Ads_kid=arrIntern[2];Ads_bid=0;Ads_xl=m;Ads_yl=n;lB(jA[Ads_sec]+'/dat/cjf/'+wB(Ads_iid)+'.js');}else
{vA='';wA=0;eB();}}function jB(p)
{var q=[];var r=p.length;var s;for(s=0;s<r;s+=2)
q[s/2+1]=Ads_CountUrl+escape(p[s+1])+'&bidx='+p[s];return q;}function SAS()
{var t='undefined';if(typeof(Ads_cmd)==t) Ads_cmd='';if(typeof(Ads_kid)==t) Ads_kid=0;if(typeof(Ads_bid)==t) Ads_bid=0;if(typeof(Ads_xl)==t) Ads_xl=0;if(typeof(Ads_yl)==t) Ads_yl=0;if(typeof(Ads_xp)==t) Ads_xp='';if(typeof(Ads_yp)==t) Ads_yp='';if(typeof(Ads_opt)==t) Ads_opt=0;if(typeof(Ads_wrd)==t) Ads_wrd='';if(typeof(Ads_prf)==t) Ads_prf='';if(typeof(Ads_par)==t) Ads_par='';if(typeof(Ads_cnturl)==t) Ads_cnturl='';if(typeof(Ads_ref)==t) Ads_ref=0;Ads_cmd=Ads_cmd.toLowerCase();if(Ads_ref==0)
Ads_ref=IAS[12];if(Ads_ref>0)
{document.write('<iframe src="'+jA[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid+'&kid='+Ads_kid+'&bid='+Ads_bid+'&xl='+Ads_xl+'&yl='+Ads_yl+'&xp='+Ads_xp+'&yp='+Ads_yp+'&opt='+Ads_opt+'&wrd='+escape(Ads_wrd)+'&prf='+escape(Ads_prf)+'&par='+escape(Ads_par)+'&cnturl='+Ads_cnturl+'&sec='+Ads_sec+'&ref='+Ads_ref+'" width="'+Ads_xl+'" height="'+Ads_yl+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');Ads_ref=0;return;}vB(3,'Start for Adspot '+Ads_iid);aD();bA='';cA='';eA=0;fA=0;gA='';dA=-1;if((typeof(Ads_T)=='undefined')||(typeof(Ads_T[5])=='undefined'))
Ads_T=[0,0,'',0,0,'','','','',0,0,0];if(Ads_nid==7)
KAS[KAS.length]=[-1,100,-1,100,[],0,0,0,0,100];vB(3,'Select campaigns');if((Ads_kid==0)||(Ads_kid==''))
dA=cC();else
{vB(1,'Preselected campaign',Ads_kid);r=KAS.length;dA=0;while((dA<r)&&(KAS[dA][0]!=Ads_kid))
dA++;if(dA==r)
dA=-1;}if((Ads_opt&256)!=0)
{if(dA!=-1)
Ads_skid=KAS[dA][0];else
Ads_skid=0;vB(1,'Skipping delivery,selected campaign:',Ads_skid);}else
{if(dA!=-1)
{eA=KAS[dA][0];fA=KAS[dA][6];if(fA!=0)
gA='&sid='+fA;vB(1,'Selected campaign',eA+'('+fA+')');if(eA>0)
{vB(1,'BJF-load start','');lB(jA[Ads_sec]+'/dat/bjf/'+wB(eA)+'.js');vB(1,'BJF-load ende','');}else
DAS();}else
{vB(1,'no campaign selected!');DAS();}}}function DAS()
{vB(3,'Select banner for campaign '+eA);var u,r,i,v,w,x;var y='';var z=['_blank','_self','_parent','_top'];var k=0;var A,m,n;if(IAS[9]==1)
{A='adsolut.gif';m=234;n=60;}else
{A='trpix.gif';m=1;n=1;}var B=1;var h='http://www.falkag.de';// Ziel-Url
var C='Falk AdSolution';var D=0;var E='';var F='';var G='';var H='';var I='';var J=0;var K=0;var L=1;var M=2;var l='';var N='';var p=[];var O=0;var P='';var Q,R,S,T,U,V,W,X,Y,Z;if(eA!=0)
{if((Ads_bid==0)||(Ads_bid==''))
u=dC(dA,eA);else
{r=BAS.length;u=0;while((BAS[u][0]!=Ads_bid)&&(u<r))
u++;if(u==r)
u=-1;}if(u!=-1)
k=BAS[u][0];}if(k>0)
{B=BAS[u][3];A=BAS[u][4];h=BAS[u][5];C=BAS[u][6];D=BAS[u][12];E=BAS[u][7];F=BAS[u][8];G=BAS[u][9];H=BAS[u][10];I=BAS[u][11];m=BAS[u][13];n=BAS[u][14];J=BAS[u][15];K=BAS[u][16];L=BAS[u][17];M=BAS[u][18];l=BAS[u][19];N=BAS[u][20];p=BAS[u][22];O=BAS[u][23];P=BAS[u][24];y=cD(eA,dA,k,u,((D&4096)>0));Ads_klist+=eA+'#';x=KAS[dA][4][25];if(x>0)
{if(typeof(Ads_fcount[x])=='undefined')
Ads_fcount[x]=1;else
Ads_fcount[x] ++;}}if(eA==-1)
{eA=99999999;k=99999999;}Ads_skid=eA;Ads_sbid=k;vB(1,'Selected campaign',eA);vB(1,'Selected banner',k);vB(3,'Delivery and display of the banner');F=(F=='')?h:F;Q=(D&24);R=z[D&3];U=((D&64)>0)&&((Ads_opt&64)==0);S=(D&128)>0;T=(D&512)>0;V=((D&1024)>0)&&Ads_ModulEffects;W=((D&8192)>0);X=(D&2048)>0;Y=(N.length>0);m=(Ads_xl>0)?Ads_xl:m;n=(Ads_yl>0)?Ads_yl:n;J=(Ads_xp!='')?Ads_xp:J;K=(Ads_yp!='')?Ads_yp:K;hA=(D&4096)>0;Ads_opt|=(D&16384)>0?64:0;Ads_opt|=IAS[3]*32;Ads_Timestamp=sB();h=fB(h);F=fB(F);if(Ads_cnturl!='')
{Z=uB(Ads_cnturl,'[url]',escape(h));h=uB(Z,'[url_plain]',h);Z=uB(Ads_cnturl,'[url]',escape(F));F=uB(Z,'[url_plain]',F);}i=oB(eA,k,y);vB(1,'Count-String',i);if((B==3)||(B==4))
{Ads_LinkUrl=h;Ads_CountUrl=hB('',i);Ads_ClickUrl=Ads_CountUrl+escape(h);Ads_MultiUrl=jB(p);Ads_ViewCode=qB(i);Ads_ViewUrl=pB()+i;}if(B==1)
G=mA[Ads_sec]+'/dat/bgf/'+A;if(xA.length!=0)
{if(!S)
{S=xA[0];U=xA[1];T=xA[2];M=xA[3];V=xA[4];W=xA[5];}if(!Y)
{Y=xA[6];N=xA[7];}J=xA[8];K=xA[9];Q=xA[10];IAS[2]=xA[11];IAS[11]=xA[12];xA=[];}if(B==5)
{xA=[S,U,T,M,V,W,Y,N,J,K,Q,IAS[2],IAS[11]];S=false;Y=false;IAS[2]=0;}if((Ads_cmd=='lnk')&&(B!=5))
{self.location.href=hB(h,i);S=false;Y=false;B=6;return;}if(S&&((P=='')||(B!=3)))
{v=fG(m,n,J,K,Q,U,T,M,V,W);if(U)
{if(window.innerHeight)
{m=v.innerWidth;n=v.innerHeight;}else
{m=v.document.body.clientWidth;n=v.document.body.clientHeight;}}if(T)
window.setTimeout('v.blur();',M*1000);}else
v=window;if(Ads_ModulEffects&&Y)
{if(Q==16)
Q=1;else if(Q==24)
Q=2;else
Q=0;mF(Ads_iid,m,n,J,K,Q,N,S,v);nF(Ads_iid,Ads_sec);}vB(1,'Banner-Typ/PopUp',B+'/'+S);if(B<2)
zF(v,S,i,G,h,R,m,n,C);else if(B==2)
aG(v,S,i,A,h,R,m,n,C,E,F,X,L);else if(B==3)
bG(v,S,i,h,eA,k,y,Y,m,n,O,P);else if(B==4)
cG(v,S,i,H,I,Y,m,n);else if(B==5)
iB(eA,k,l,m,n);vB(3,'Banner-display finished');tC();if(Ads_ModulEffects&&Y)
oF(Ads_iid);if(B!=5)
eB();Ads_idl+='#'+Ads_iid+'#';if((IAS[2]>0)&&(Ads_idl.indexOf('#'+IAS[2]+'#')==-1)&&(IAS[11]>(Math.random()*100)))
{vB(1,'Load combined adspot',IAS[2]);Ads_kid=0;Ads_bid=0;Ads_xl=0;Ads_yl=0;lB(jA[Ads_sec]+'/dat/cjf/'+wB(IAS[2])+'.js');}}function CAS()
{if(typeof(Ads_debug)=='undefined') Ads_debug=0;var Aa=new Date(Ads_T[9]);var Ba=new Date();Ads_T[9]=Aa-Ba;var Ca=Ads_T[0]+'#'+Ads_T[1]+'#'+Ads_T[2]+'#'+Ads_T[3]+'#'+Ads_T[4]+'#'+Ads_T[5]+'#'+Ads_T[6]+'#'+escape(Ads_T[7])+'#'+escape(Ads_T[8])+'#'+Ads_T[9]+'#'+Ads_T[10]+'#'+Ads_T[11];document.cookie='ASLTRG='+Ca+mB(60*24);vB(1,'Load targeting-infos from server',Ca);}function LAS(Da)
{Ads_iid=0;var i='pth='+Da+'&xl='+Ads_xl+'&yl='+Ads_yl;if(typeof(Ads_channels)!='undefined')
i+='&chn='+escape(Ads_channels);hA=false;document.write(qB(i));}function kB()
{iA=new Date();if(typeof(Ads_debug)=='undefined') Ads_debug=0;if(typeof(Ads_sec)=='undefined') Ads_sec=0;if(typeof(Ads_klist)!='string') Ads_klist='';if(typeof(Ads_fcount)!='object') Ads_fcount=[];if(typeof(Ads_idl)!='string') Ads_idl='';vB(3,'Global Init');var Ca=document.cookie+';';var Ea=(Ca.indexOf('BSUID=')!=-1);var Fa=Ca.indexOf('ASLTRG=');var Ga,R;if(Fa!=-1)
{Ga=Ca.indexOf(';',Fa);R=Ca.substring(Fa+7,Ga);Ads_T=R.split('#');Ads_T[7]=unescape(Ads_T[7]);Ads_T[8]=unescape(Ads_T[8]);vB(1,'Load targeting-infos from cookie',R);}else
{vB(1,'#-#ASLDATA-load start','');lB(lA[Ads_sec]+(Ea?('?rdm='+sB()):''));vB(1,'#-#ASLDATA-load ende','');}}kB();