// Falk AdSolution - Copyright (c) 2003 by Falk eSolutions AG - All rights reserved
function yF(Me,Lg)
{return (Me==0)?'':' '+Lg+'="'+Me+'"';}function zF(v,S,i,G,h,R,m,n,C)
{G=fB(G);if(S)
dG(v,C);v.document.write('<a href="'+hB(h,i) +'" target="'+R+'" onmouseover="self.status=\'AdSolution\';return true;" onmouseout="self.status=\'\';return true;">');v.document.write('<img src="'+G+'"'+yF(m,'width')+yF(n,'height')+' border="0" id="Ads_img'+Ads_iid+'" name="Ads_img'+Ads_iid+'" alt="'+C+'"></a>');rB(v,i);if(S)
eG(v);vA='';wA=0;}function aG(v,S,i,A,h,R,m,n,C,E,F,X,L)
{if(S)
dG(v,C);h=hB(h,i);F=hB(F,i);A=mA[Ads_sec]+'/dat/bgf/'+A;E=mA[Ads_sec]+'/dat/bgf/'+E;aB=h;bB=hB('',i);var Mg=A+'?clickTag='+escape(h)+'&url='+escape(h);vB(1,'Flash-Url',Mg);var Xa;if(L<=yB())
{v.document.write('<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=3,0,0,0" id=banner'+yF(m,'width')+yF(n,'height')+'">');v.document.write('<PARAM NAME=movie VALUE="'+Mg+'"><PARAM NAME=play VALUE=true><PARAM NAME=autoplay VALUE=true><PARAM NAME=wmode VALUE=opaque><PARAM NAME=quality VALUE=autohigh><PARAM name=scale value=exactfit>');v.document.write('<EMBED src="'+Mg+'" quality=autohigh autoplay=true play=true wmode=opaque scale=exactfit swLiveConnect=TRUE'+yF(m,'width')+yF(n,'height')+' TYPE="application/x-shockwave-flash" PLUGINSPAGE="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash"></EMBED></OBJECT>');}else
{v.document.write('<a href="'+F+'" target="'+R+'" onmouseover="self.status=\'AdSolution\';return true;" onmouseout="self.status=\'\';return true;"><img src="'+E+'"'+yF(m,'width')+yF(n,'height')+' border="0" alt="'+C+'"></a>');}rB(v,i);if(S)
eG(v);vA='';wA=0;}function bG(v,S,i,h,j,k,y,Y,m,n,O,P)
{var A=jA[Ads_sec]+'/dat/brf/'+wB((O==0)?k:O);var Ng,Xd;iid=Ads_iid;bid=k;rdm=nB(j,k,y);if(S||(Y&&tA))
{var Og='';for(Xd=0;Xd<Ads_MultiUrl.length;Xd++)
Og+=Ads_MultiUrl[Xd]+'*';Ng=Ads_wid+'#'+Ads_iid+'#'+j+'#'+k+'#'+Ads_xwid+'#'+Ads_xiid+'#'+Ads_wrd+'#'+Ads_prf+'#'+Ads_par+'#'+Ads_Timestamp+'#'+rdm+'#'+gB()+'#'+Ads_LinkUrl+'#'+Og+'#'+pB();}if(S&&(P!=''))
{window.open(A+'.html?'+escape(Ng),P);}else if(S)
{vB(1,'Pop',A+'.html?'+escape(Ng));v.location.href=A+'.html?'+escape(Ng);}else if(Y&&tA)
{vB(1,'Ifr',A+'.html?'+escape(Ng));document.write('<iframe src="'+A+'.html?'+escape(Ng)+'" width="'+m+'" height="'+n+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');}else
{vB(1,'Jsc',A+'.js');lB(A+'.js');}vA='';wA=0;}function cG(v,S,i,H,I,Y,m,n)
{I=fB(unescape(I));H=fB(unescape(H));vB(1,'Redirect',I+'/'+H);if(S)
v.location.href=H;else
{if(Y&&tA)
document.write('<iframe src="'+H+'" width="'+m+'" height="'+n+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');else
lB(I);}rB(window,i);vA='';wA=0;}function dG(v,C)
{v.document.open();v.document.write('<html><head><title>'+C+'</title></head><body topmargin="0" leftmargin="0" rightmargin="0" marginwidth="0" marginheight="0"><table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0" align="center"><tr><td valign="middle"><center>');}function eG(v)
{v.document.write('</center></td></tr></table></body></html>');v.document.close();}function fG(m,n,J,K,Q,U,T,M,V,W)
{var w='locationbar=no,directories=no,statusbar=no,toolbar=no,location=no,menubar=no,personalbar=no';var Pg='Ads_Popup'+Ads_iid;var Qg,Rg;var Sg=0;var Tg=0;if(U)
{if (rA)
{Sg=10;Tg=30;}else if (sA)
{Sg=20;Tg=35;}w+=',scrollbars=no,resizable=no,width='+(screen.availWidth-Sg)+',height='+(screen.availHeight-Tg)+',screenX=0,screenY=0';if(qA)
w='fullscreen=yes';}else
{if(V)
w+=',resizable=yes,width=90,height=70,innerWidth=90,innerHeight=70';else
w+=',resizable=no,width='+m+',height='+n;if(W)
w+=',scrollbars=yes';else
w+=',scrollbars=no';if(Q==16)
{J=(screen.width-m-25)*J/100;K=(screen.height-n-50)*K/100;}else if(Q==24)
{J=(screen.width-m-25)*Math.random();K=(screen.height-n-50)*Math.random();}if (!tA)
w+=",screenX="+J+",screenY="+K;else
w+=",left="+J+",top="+K;}if((Ads_opt&32)>0)
Pg+=Math.round(Math.random()*100000);if((Ads_opt&64)>0)
w='locationbar=yes,scrollbars=yes,directories=yes,statusbar=yes,toolbar=yes,location=yes,menubar=yes,personalbar=yes,resizable=yes';vB(1,'PopUp open START','');v=open('',Pg,w);vB(1,'PopUp open END','');if(U&&(!qA))
v.moveTo(0,0);if(T&&(M==0))
v.blur();else if(T)
v.setTimeout('window.blur();',M*1000);if(V)
vF(v,m,n);return v;}// Falk AdSolution - Copyright (c) 2003 by Falk eSolutions AG - All rights reserved
var vC=[];function wC(Fe,Ge)
{while(Fe.length>800)
Fe=Fe.substr(0,Fe.lastIndexOf('#',Fe.length-2)+1);vC[Ge]=Fe;}function xC(Ge,Ua)
{var He='111';var Ie='@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`';var r=0;var Je='#'+Ua+':';var Fe=vC[Ge];var Ke='';var Q=Fe.indexOf(Je);var Le=new Date();var Me,Ne,Oe,Pe,Fc;if(Fe=='')
Fe='#';if(Q>-1)
{Ne=Fe.substr(Q+Je.length,3+Ge);if(Q>0)
Ke=Fe.substr(0,Q);Me=Fe.length-Q-Je.length-3-Ge;if(Me>0)
Ke+=Fe.substr(Q+Je.length+3+Ge,Me);Fe=Ke;Oe=new Date(Ie.indexOf(Ne.charAt(0))+2000,Ie.indexOf(Ne.charAt(1))-1,Ie.indexOf(Ne.charAt(2)));Le.setHours(0);Le.setMinutes(0);Le.setSeconds(0);Pe=(Le.getTime()-Oe.getTime())/1000/60/60/24;if(Pe<1) He='0';else He='1';if(Pe<7) He+='0';else He+='1';if(Pe<30) He+='0';else He+='1';if(Ge==1)
r=Ie.indexOf(Ne.charAt(3));}Ne='#'+Ua+':';Fc=Le.getYear();if(Fc<1900)
Fc+=1900;Ne+=Ie.charAt(Fc-2000);Ne+=Ie.charAt(Le.getMonth()+1);Ne+=Ie.charAt(Le.getDate());if(Ge==1)
{r++;if(r>21)
r=21;Ne+=Ie.charAt(r);He+=Ie.charAt(r);}Fe=Ne+Fe;wC(Fe,Ge);return He;}function yC(Je,Ge,Qe)
{var Fa,Ga,Me,Re,Se;var Fe=vC[Ge];var Ke='';var Te='';var Ue=-1;if(Fe=='')
Fe='#';Je='#'+Je+'-';Fa=Fe.indexOf(Je);if(Fa!=-1)
Ga=Fe.indexOf('#',Fa+1);if((Fa!=-1)&&(Ga!=1))
{Re=Fe.substring(Fa+Je.length,Ga);if(Fa>0)
Ke=Fe.substr(0,Fa);Me=Fe.length-Ga;if(Me>0)
Ke+=Fe.substr(Ga,Me);Fe=Ke;if(Ge==6)
{Se=Re.split('-');Te=Se[0];Re=Se[1];}Ue=Qe-parseInt(Re,10);if(Ue>1200)
Ue=-1;}vC[Ge]=Fe;return [Ue,Te];}function zC(j)
{var Ve=new Date();var Ue=Ve.getHours()*60*60+Ve.getMinutes()*60+Ve.getSeconds();var We,Xe;We=yC(Ads_wid,6,Ue);Xe=yC(j,5,Ue);var Ye=(We[0]==-1);var Ze=(Xe[0]==-1);var Af=(Ye?'1':'0')+(Ze?'1':'0');if(!Ye)
Af+=tB(We[0],4)+We[1];wC('#'+Ads_wid+'-'+Ads_iid+'-'+Ue+vC[6],6);wC('#'+j+'-'+Ue+vC[5],5);return Af;}function aD()
{vB(2,'Read Cookies');var s,Kd,Bf,Cf,Ge;var Ca=document.cookie;var Df=Ca.split(';');var r=Df.length;vC=['','','','','','','','','',''];for(s=0;s<r;s++)
{Ge=-1;Cf=Df[s].split('=');Kd=Cf[0];Bf=Cf[1];if(Kd.charAt(0)==' ')
Kd=Kd.substr(1,Kd.length-1);if(Kd=='KIDYMD')
vC[1]=Bf;else if(Kd=='WIDYMD')
vC[0]=Bf;else if(Kd=='BSUID')
vC[3]=Bf;else if(Kd=='BNDWDT')
vC[4]=Bf;else if(Kd=='VISKAM')
vC[5]=Bf;else if(Kd=='VISWEB')
vC[6]=Bf;else if(Kd.substr(0,3)=='KID')
Ge=2;else if(Kd.substr(0,3)=='WID')
Ge=7;else if(Kd.substr(0,3)=='NID')
Ge=8;else if(Kd.substr(0,3)=='BID')
Ge=9;if(Ge>-1)
{Kd=Kd.substr(3,Kd.length-3);vC[Ge]+='#'+Kd+':'+Bf+'#'+Kd+':';}}vC[2]='X'+vC[2]+'X';vC[7]='X'+vC[7]+'X';vC[8]='X'+vC[8]+'X';vC[9]='X'+vC[9]+'X';vB(1,'KIDYMD',vC[1]);vB(1,'WIDYMD',vC[0]);vB(1,'KID' ,vC[2]);vB(1,'BID' ,vC[9]);vB(1,'WID' ,vC[7]);vB(1,'NID' ,vC[8]);vB(1,'BSUID' ,vC[3]);vB(1,'BNDWDT',vC[4]);vB(1,'VISKAM',vC[5]);vB(1,'VISWEB',vC[6]);}function bD(j,Nb)
{var Ef='';if(KAS[Nb][4][4]>0)
Ef=mB(KAS[Nb][4][5]);else if((KAS[Nb][5]&1)>0)
Ef=mB(20);if(Ef!='')
document.cookie='KID'+j+'='+parseInt(dD(j,2)+1,10)+Ef;}function cD(j,Nb,k,u,Ff)
{var y;bD(j,Nb);if(BAS[u][2][4]>0)
document.cookie='BID'+k+'='+parseInt(dD(k,9)+1,10)+mB(BAS[u][2][5]);if(((KAS[Nb][4][22]&1)>0)&&(IAS[4]>0))
document.cookie='WID'+Ads_wid+'='+parseInt(dD(Ads_wid,7)+1,10)+mB(IAS[5]);if(((KAS[Nb][4][22]&2)>0)&&(IAS[6]>0))
document.cookie='NID'+Ads_nid+'='+parseInt(dD(Ads_nid,8)+1,10)+mB(IAS[7]);y=xC(1,j);y='&bls3='+y.substr(0,3)+xC(0,Ads_wid)+y.substr(3,1);document.cookie='WIDYMD='+vC[0]+mB(60*24*30);document.cookie='KIDYMD='+vC[1]+mB(60*24*30);y+='&bls4='+zC(j);document.cookie='VISKAM='+vC[5]+mB(20);document.cookie='VISWEB='+vC[6]+mB(20);if(vC[3]=='')
vC[3]=sB();else
y+='&uid=1';document.cookie='BSUID='+vC[3]+mB(60*24*30);return y;}function dD(Ua,Nc)
{var Zb=vC[Nc].split('#'+Ua+':');if(Zb.length==3)
return parseInt(Zb[1],10);else
return 0;}// Falk AdSolution - Copyright (c) 2003 by Falk eSolutions AG - All rights reserved
function zB(Ya,Za)
{vB(1,'Select-Value',Za);var s=0;var r=Ya.length;if(r==0)
return -1;while((s<r-1)&&(Za>Ya[s][1]))
{Za-=Ya[s][1];s++;}return Ya[s][0];}function aC(Ab,Bb,Cb)
{var s,Db,Eb,Fb;vB(1,'---- CLOSE OLD PRIORITY','');vB(1,'share-sum of all successfully campaigns',Ab);vB(1,'free shares before this priority',Cb);if(Ab>Cb)
{Db=Cb/Ab;for(s=Bb;s<oA.length;s++)
oA[s][1]*=Db;Ab=Cb;}Cb-=Ab;vB(1,'free shares after this priority',Cb);return Cb;}function bC()
{vB(0,'campaign-filtering');var Gb,Hb,Ib,Jb,Kb;var Lb=-2;var Mb=KAS.length;var Cb=100;var Nb,j,Fb,Ob,Pb,Qb,Rb,Sb,Tb;var Ab;var Bb;oA=[];for (Nb=0;Nb<Mb;Nb++)
{Kb=((KAS[Nb][5]&2)>0);if(KAS[Nb][2]!=Lb)
{if(Lb!=-2)
Cb=aC(Ab,Bb,Cb);Lb=KAS[Nb][2];vB(1,'---- START NEW PRIORITY',Lb);Ab=0;Bb=oA.length;}vB(1,'<b>campaign '+KAS[Nb][0]+'</b>',KAS[Nb]);Ob=KAS[Nb][8];Pb=KAS[Nb][10];Qb=IAS[10];if((Qb-Pb)>0)
Ob=Ob*Qb/(Qb-Pb);Fb=KAS[Nb][1];if(Ob<=0)
Ob=Fb;Rb=Fb/Ob;if((Rb>10)||(Rb<0.1))
Rb=1;Sb=KAS[Nb][3];Fb=Fb*Rb*100/((Sb<=0)?100:Sb);Jb=KAS[Nb][4];Gb=sC(Jb,0,KAS[Nb][0]);Ib=false;if(Jb.length>0)
{Ib=((Jb[0]==0)&&!((Jb[2]==0)&&(Jb[3]==1439)));Hb=(!Ib||qC(Jb[2],Jb[3]));if(Ib)
Fb=Fb*100/KAS[Nb][9];if(Gb&&!Hb&&!Kb)
bA+='9'+KAS[Nb][0]+'-';Gb=(Gb&&Hb);}vB(1,'timetargeting,successful',(Ib)+','+(Hb));if(Kb&&Gb)
{vB(2,'<font color=#ff8000>testcase successful</font>');j=KAS[Nb][0];cA+=j+'-';bD(j,Nb);}else if(Gb)
{vB(2,'<font color=#008000>successful</font>');oA[oA.length]=[Nb,Fb,Ib,Fb];Ab+=Fb;}else
{vB(2,'<font color=#ff0000>failed</font>');}}Cb=aC(Ab,Bb,Cb);}function cC()
{bC();var Ub,Nb,s,Fb;var Mb=oA.length;var Vb=0;vB(0,'campaign-selection');for (Nb=0;Nb<Mb;Nb++)
{s=oA[Nb][0];Fb=oA[Nb][1];Ub=Math.round(Fb/oA[Nb][3]*10)-1;if(Ub>9)
Ub=9;if((Ub>0)&&(KAS[s][0]>0))
bA+=Ub+''+KAS[s][0]+'-';Vb+=Fb;vB(1,'Campaign,Chance,ShareActual,Share,ShareNew',KAS[s][0]+' ,'+KAS[s][3]+' ,'+KAS[s][8]+' ,'+KAS[s][1]+' ,'+Fb);}vB(1,'Chances',bA);return zB(oA,Vb*Math.random());}function dC(Nb,j)
{var Wb=[];var Xb=BAS.length;var Yb=((KAS[Nb][5]&1)>0);var Vb=0;var u,Fb,Zb,Ac,Bc,Cc;var Dc=true;for (u=0;u<Xb;u++)
{vB(1,'<b>Banner '+BAS[u][0]+'</b>',BAS[u]);strInhalt=BAS[u][21];Cc=((strInhalt.length<3)||(strInhalt.indexOf('#'+Ads_iid+'#')>-1));if(((Ads_xl>1)||(Ads_yl>1))&&((BAS[u][13]>1)||(BAS[u][14]>1)))
{Dc=((Ads_xl==BAS[u][13])&&(Ads_yl==BAS[u][14]));vB(1,'Bannersize',Dc);}if(Dc&&Cc&&sC(BAS[u][2],1,BAS[u][0]))
{Fb=BAS[u][1];vB(2,'<font color=#008000>successful</font></b>,Anteil:'+Fb+'<b>');Wb[Wb.length]=[u,Fb];Vb+=Fb;}else
{vB(2,'<font color=#ff0000>failed</font>');}}Xb=Wb.length;if(Yb)
{Ac=dD(j,2);if(Xb>0)
u=Wb[Ac%Xb][0];else
u=-1;}else
u=zB(Wb,Vb*Math.random());return u;}// Falk AdSolution - Copyright (c) 2003 by Falk eSolutions AG - All rights reserved
var eC=false;var fC;var gC;var hC=0;function iC(Ec)
{return tB(Ec.getHours(),2)+':'+tB(Ec.getMinutes(),2)+':'+tB(Ec.getSeconds(),2);}function jC(Ec)
{var Fc=Ec.getYear();if(Fc<1900)
Fc+=1900;return tB(Fc,4)+'-'+tB(Ec.getMonth()+1,2)+'-'+tB(Ec.getDate(),2);}function kC()
{if(eC)
return;var Gc,Hc,Ic,s,Jc;var Kc=new Date();var Lc=new Date();Lc.setTime(Kc-0+parseInt(Ads_T[9],10));Gc=vC[1].split('#');Hc=Gc.length-1;Ic=',';for(s=1;s<Hc;s++)
{Jc=Gc[s].split(':');Ic+=Jc[0]+',';}eC=true;fC=';keyword='+escape(Ads_wrd) +';user-domain='+Ads_T[5] +';user-ip='+Ads_T[6] +';url='+escape(window.location.href) +';referrer='+escape(document.referrer) +';accept-language='+escape(Ads_T[7]) +';accept-charset='+escape(Ads_T[8]) +';user-agent='+escape(navigator.userAgent) +';browser-name='+escape(navigator.appName) +';browser-version='+escape(navigator.appVersion) +';flash-version='+yB() +';user-day='+(Kc.getDay()==0?7:Kc.getDay()) +';user-time='+iC(Kc) +';user-date='+jC(Kc) +';server-day='+(Lc.getDay()==0?7:Lc.getDay()) +';server-time='+iC(Lc) +';server-date='+jC(Lc) +';campaigns='+Ic +';';if(navigator.appVersion.substring(0,1)>'3')
fC+='java='+(navigator.javaEnabled()?'1':'0') +';screen-width='+screen.width +';screen-height='+screen.height +';window-width='+(window.innerWidth?window.innerWidth:document.body.clientWidth) +';window-height='+(window.innerWidth?window.innerHeight:document.body.clientHeight) +';color-depth='+screen.colorDepth +';';vB(1,'Environment values',fC);}function lC(Mc,r,Ua,Nc,Oc,Pc)
{var Qc;if((r>0)&&(Mc>0))
{Qc=(dD(Ua,Nc)<r);if((Qc?1:0)==Oc)
return Oc;gC[Pc]=Qc;}return 2;}function mC(Rc,Sc,Tc,Oc,Pc)
{var Qc;if(Rc.length>1)
{Qc=(Rc.indexOf('#'+Ads_T[Sc]+'#')!=-1);Qc=Tc>0?!Qc:Qc;if((Qc?1:0)==Oc)
return Oc;gC[Pc]=Qc;}return 2;}function nC(Rc,Tc,Oc,Uc,Pc)
{if(Rc=='')
return 2;var s,Pa,Vc,Wc,Xc,Yc,Zc,Ad,Bd;var Qc=false;Rc=Rc.substr(1,Rc.length-2);var Jb=Rc.split('#');var r=Jb.length;if(r>0)
{if(Uc)
{strTrenner='!"%&\'()*+,-./:;<=>?@[\\]^_{|}~§ ';Pa='';Yc=Ads_wrd.length;for(s=0;s<Yc;s++)
{Xc=Ads_wrd.charAt(s);if(strTrenner.indexOf(Xc)!=-1)
Xc='#';Pa+=Xc;}Pa='#'+Pa.toLowerCase()+'#';Vc=Pa;}else
{Pa='#'+Ads_T[5]+'#';Vc='#'+Ads_T[6]+'#';}for(s=0;(s<r)&&(Qc==false);s++)
{Ad=Jb[s];Zc=false;if(Ad.substring(0,1)=='$')
{Ad=Ad.substring(1,Ad.length-1);Zc=true;}Wc=false;Bd=Pa;if(Ad.substring(0,1)=='!')
{Ad=Ad.substring(1,Ad.length-1);Bd=Vc;Wc=true;}if(Uc)
Ad='#'+Ad;if(!Wc)
Ad+='#';Qc=(Bd.indexOf(Ad)!=-1);if(Zc&&Qc)
{Qc=false;s=r;}}Qc=Tc>0?!Qc:Qc;if((Qc?1:0)==Oc)
return Oc;gC[Pc]=Qc;}return 2;}function oC(Cd,Dd)
{var Ed=[];var Fd=0;var s,Gd;var r=Cd.length;for(s=0;s<r;s++)
{Gd=Cd[s];if(Gd>=0)
{Ed[Fd]=Dd[Gd];Fd++;}else if(Gd==-2)
{Fd--;Ed[Fd-1]=(Ed[Fd-1]&&Ed[Fd]);}else if(Gd==-4)
{Fd--;Ed[Fd-1]=(Ed[Fd-1]||Ed[Fd]);}else if(Gd==-3)
Ed[Fd-1]=(!Ed[Fd-1]);}return Ed[Fd-1];}function pC(Jb,Hd,Tc,Id,Jd,Oc,Pc)
{var Qc,Kd,Ld,Md,Nd,Od,B,Pd;var Qd,Rd;var s=0;var r=Jb.length;var Dd=[];for(s=0;s<r;s++)
{Kd=Jb[s][0];Ld=Jb[s][1];B=Jb[s][2];Pd=Jb[s][3];vB(1,'Profile/Environment -> Name,WishedValue,Type,Operator',Kd+','+Ld+','+B+','+Pd);Qd=Hd.indexOf(';'+Kd+'=');if(Qd>-1)
{Rd=Hd.indexOf(';',Qd+1);if(Rd>Qd)
Od=unescape(Hd.substring(Qd+2+Kd.length,Rd));else
Od='';if(B==5)
B=1;if(B==1)
Md=0;else
Md='';if((Pd==9)||(Pd==10))
{Nd=Ld.split(';');if(Nd.length==2)
{Ld=Nd[0];Md=Nd[1];}else
Pd=0;}if(B==1)
{Od=parseFloat(Od);Ld=parseFloat(Ld);Md=parseFloat(Md);}if((Pd>5)&&(Pd<9))
{Od=Od.toLowerCase();Ld=Ld.toLowerCase();}if(Pd==0)
Qc=(Od==Ld)
else if(Pd==1)
Qc=(Od!=Ld)
else if(Pd==2)
Qc=(Od<Ld)
else if(Pd==3)
Qc=(Od<=Ld)
else if(Pd==4)
Qc=(Od>Ld)
else if(Pd==5)
Qc=(Od>=Ld)
else if(Pd==6)
Qc=(Od.indexOf(Ld)>-1);else if(Pd==7)
Qc=(Od.indexOf(Ld)<0);else if(Pd==8)
Qc=Od.substr(0,Ld.length-1)==Ld;else if(Pd==9)
Qc=((Od>=Ld)&&(Od<=Md))
else if(Pd==10)
Qc=((Od<Ld)||(Od>Md))
}else
{Qc=false;}vB(1,'Profile/Environment -> result',Qc);if(Id==2)
Dd[s]=Qc;else
{if((Qc&&(Id==1))||(!Qc&&(Id==0)))
s=r;}}if(Id==2)
Qc=oC(Jd,Dd);Qc=Tc>0?!Qc:Qc;if((Qc?1:0)==Oc)
return Oc;gC[Pc]=Qc;return 2;}function qC(Sd,Td)
{var Kc=new Date();var Lc=new Date();Lc.setTime(Kc-0+parseInt(Ads_T[9],10));var Ud=Lc.getHours()*60+Lc.getMinutes();if(Sd<Td)
Qc=((Ud>=Sd)&&(Ud<=Td));else
Qc=((Ud>=Sd)||(Ud<=Td));return Qc;}function rC(Vd,Wd)
{var r=Vd.length;var Xd;if(typeof(Vd.Ads_klist)=='string')
Wd+=Vd.Ads_klist+'#';for(Xd=0;Xd<r;Xd++)
Wd=rC(Vd.frames[Xd],Wd);return Wd;}function sC(Jb,B,Ua)
{var Oc=Jb[0];var Tc=Jb[1];var Qc,Yd,Zd,Ic,Gc,Hc,s,Ae,Be,Ce,De;gC=[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true];if(Jb.length==0)
return true;vB(1,'Targeting',Jb);if((Oc>0)||(B==1))
{Qc=qC(Jb[2],Jb[3]);vB(1,'Time',Qc);if((Qc?1:0)==Oc)
return Qc;gC[0]=Qc;}Yd=lC(1,Jb[4],Ua,(B==0)?2:9,Oc,1);vB(1,'Frequency (Max:'+Jb[4]+',actual:'+dD(Ua,(B==0)?2:9)+')',Yd!=0);if(Yd<2)
return Yd==1;if(B==0)
{Yd=lC(Jb[22]&1,IAS[4],Ads_wid,7,Oc,12);vB(1,'Frequency (WebSite)',Yd!=0);if(Yd<2)
return Yd==1;Yd=lC(Jb[22]&2,IAS[6],Ads_nid,8,Oc,13);vB(1,'Frequency (Network)',Yd!=0);if(Yd<2)
return Yd==1;}Yd=mC(Jb[6],0,Tc&1,Oc,2);vB(1,'OS',Yd!=0);if(Yd<2)
return Yd==1;Yd=mC(Jb[7],1,Tc&2,Oc,3);vB(1,'Browser',Yd!=0);if(Yd<2)
return Yd==1;Yd=mC(Jb[8],2,Tc&4,Oc,4);vB(1,'Country',Yd!=0);if(Yd<2)
return Yd==1;Yd=mC(Jb[9],3,Tc&8,Oc,5);vB(1,'Provider',Yd!=0);if(Yd<2)
return Yd==1;if(Jb[10].length>1)
{Qc=((Jb[10].indexOf('#'+Ads_T[4]+'#')!=-1)||(Jb[10].indexOf('#%'+Ads_T[10]+'#')!=-1)||(Jb[10].indexOf('#$'+Ads_T[11]+'#')!=-1));if((Ads_nid==7)&&(Ads_T[4]<1)&&(Jb[10].indexOf('#$14658#')!=-1)) Qc=true;Qc=(Tc&16)>0?!Qc:Qc;vB(1,'Region',Qc);if((Qc?1:0)==Oc)
return Oc;gC[6]=Qc;}Yd=nC(Jb[11],Tc&32,Oc,false,7);vB(1,'Domain',Yd!=0);if(Yd<2)
return Yd==1;Yd=nC(Jb[12],Tc&64,Oc,true,8);vB(1,'Keyword',Yd!=0);if(Yd<2)
return Yd==1;if(Jb[13].length>0)
{Yd=pC(Jb[13],';'+Ads_prf+';',Tc&128,Jb[15],Jb[17],Oc,9);vB(1,'Profile',Yd!=0);if(Yd<2)
return Yd==1;}if(Jb[14].length>0)
{kC();Yd=pC(Jb[14],fC,Tc&256,Jb[16],Jb[18],Oc,10);vB(1,'Environment',Yd!=0);if(Yd<2)
return Yd==1;}if(Jb[21]>0)
{if(vC[4]=='')
{Zd=0;if(hC==0)
hC=1;}else
Zd=parseInt(vC[4],10);Qc=((Zd>=Jb[20])&&(Zd<=Jb[21]));Qc=(Tc&512)>0?!Qc:Qc;vB(1,'Bandwidth',Qc);if((Qc?1:0)==Oc)
return Qc;gC[11]=Qc;}De=Jb[23];if((B==0)&&(De>0))
{Ic=Jb[24];if(Ic.length>2)
Ic=Ic.substring(1,Ic.length-1);Gc=Ic.split('#');Hc=Gc.length;Ae=-1;strKList='#'+rC(top,'');for(s=0;(s<Hc)&&(Ae<0);s++)
{Be=(strKList.indexOf('#'+Gc[s]+'#')>-1);if((Be?1:4)==De)
Ae=0;if((Be?3:2)==De)
Ae=1;}if(Ae<0)
Ae=((De==1)||(De==4))?1:0;vB(1,'showed Camppaigns,In/Exclude',strKList+','+(Ae==1));if(Ae==Oc)
return (Ae==1);gC[14]=(Ae==1);}s=Jb[25];if(s>0)
{Be=IAS[8].indexOf('#'+s+':');if(Be!=-1)
{Be=IAS[8].indexOf(':',Be);Ce=IAS[8].indexOf('#',Be);Be=IAS[8].substring(Be+1,Ce);Ce=Ads_fcount[s];if(typeOf(Ce)=='undefined')
Ce=0;Qc=Be>Ce;vB(1,'Family',Qc);if((Qc?1:0)==Oc)
return Qc;gC[15]=Qc;}}if(Oc!=2)
return true;else
return oC(Jb[19],gC);}function tC()
{if(hC!=1)
return;document.write('<applet codebase="'+nA[Ads_sec]+'" code="bandwidth.class" id="bandwidth" name="bandwidth" width="0" height="0" mayscript="MAYSCRIPT"><param name="cbfunc" value="uC"></applet>');hC=2;}function uC(Ee)
{document.cookie='BNDWDT='+(Ee*8)+mB(60*24*7);}